### PR TITLE
helm: make scrape timeout configurable

### PR DESCRIPTION
**Pull request by SimonSimonB**
This MR makes the scrape timeout of the `ServiceMonitor` generated by the Helm chart configurable. This is helpful to fix scrape timeouts if the extended-ceph-exporter needs more time to export metrics than the global timeout settings on a cluster.

The MR also introduces a default timeout of 20s in the `values.yaml` of the Helm chart. I mainly introduced the default to be consistent with the existing `scrapeTimeout` Helm parameter that also defines a default. I'd be happy to remove the default if you prefer.

### CODE REVIEW

**Review by galexrt — APPROVED** [review]

**Comment by galexrt** [comment]
@SimonSimonB thank you for your PR!

Please bump the patch chart version to `1.3.2` here https://github.com/koor-tech/extended-ceph-exporter/blob/main/charts/extended-ceph-exporter/Chart.yaml#L18

**Comment by SimonSimonB** [comment]
Thanks for the speedy review, @galexrt !

> Please bump the patch chart version to `1.3.2` here https://github.com/koor-tech/extended-ceph-exporter/blob/main/charts/extended-ceph-exporter/Chart.yaml#L18

Sorry, forgot about that. It's bumped now.

**Comment by galexrt** [comment]
No worries! Sorry, I forgot to tell you to update the helm chart docs when bumping the version.
Please run `make helm-docs` and combine those changes with the version bump commit.

**Comment by SimonSimonB** [comment]
Sure thing! I amended the commit.

**Review by galexrt — APPROVED** [review]

**Pull request merged**
